name: Build(2.9.1_py3.12.12_cuda12.8.1_devel_ubuntu22.04)

env:
  BASE_IMAGE: "nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04"

  PYTHON_VERSION: "3.12.12"

  PYTORCH_VERSION: "2.9.1"
  PYTORCH_VERSION_SUFFIX: "+cu128"
  TORCHVISION_VERSION: "0.24.1"
  TORCHVISION_VERSION_SUFFIX: "+cu128"
  TORCHAUDIO_VERSION: "2.9.1"
  TORCHAUDIO_VERSION_SUFFIX: "+cu128"
  PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/"

  IMAGE_TAG: "2.9.1-py3.12.12-cuda12.8.1-devel-ubuntu22.04"

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ubuntu/**'
      - '.github/workflows/docker_build_2.9.1_py3.12.12_cuda12.8.1_devel_ubuntu22.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
            tool-cache: true
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            swap-storage: true

      - name: Build docker image
        run: docker/ubuntu/build.sh

      - name: Push docker image
        run: docker push spxiong/pytorch:${IMAGE_TAG}
