name: Build(2.8.0_py3.11.14_cuda12.8.1_devel_ubuntu22.04)

env:
  BASE_IMAGE: "nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04"

  PYTHON_VERSION: "3.11.14"

  PYTORCH_VERSION: "2.8.0"
  PYTORCH_VERSION_SUFFIX: "+cu128"
  TORCHVISION_VERSION: "0.23.0"
  TORCHVISION_VERSION_SUFFIX: "+cu128"
  TORCHAUDIO_VERSION: "2.8.0"
  TORCHAUDIO_VERSION_SUFFIX: "+cu128"
  PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/"

  IMAGE_TAG: "2.8.0-py3.11.14-cuda12.8.1-devel-ubuntu22.04"

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ubuntu/**'
      - '.github/workflows/docker_build_2.8.0_py3.11.14_cuda12.8.1_devel_ubuntu22.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker/ubuntu/build.sh

      - name: Push docker image
        run: docker push spxiong/pytorch:${IMAGE_TAG}
