name: Build(2.8.0_py3.10.19_cuda12.6.0_ubuntu22.04)

env:
  BASE_IMAGE: "ubuntu:22.04"

  PYTHON_VERSION: "3.10.19"

  PYTORCH_VERSION: "2.8.0"
  PYTORCH_VERSION_SUFFIX: "+cu126"
  TORCHVISION_VERSION: "0.23.0"
  TORCHVISION_VERSION_SUFFIX: "+cu126"
  TORCHAUDIO_VERSION: "2.8.0"
  TORCHAUDIO_VERSION_SUFFIX: "+cu126"
  PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/"

  IMAGE_TAG: "2.8.0-py3.10.19-cuda12.6.0-ubuntu22.04"

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ubuntu/**'
      - '.github/workflows/docker_build_2.8.0_py3.10.19_cuda12.6.0_ubuntu22.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
            tool-cache: true
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            swap-storage: true

      - name: Build docker image
        run: docker/ubuntu/build.sh

      - name: Push docker image
        run: docker push spxiong/pytorch:${IMAGE_TAG}
